apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - app-deployment.yaml
  - nginx-deployment.yaml
  # Uncomment if using Ingress:
  # - ingress.yaml

commonLabels:
  app: inventory-platform
  environment: production

